### ISSUE TITLE
What about C/C++ interop ?

### ISSUE THREAD

**Issue by kcvinker** [bamless/jstar#27]
Hi,
J star looks nice to me. Such a neat and clean language. After reading the docs, there are some questions rose.
1. Do we have automatic memory management ?
2. How do you call C/Any similar language functions from J star ? 

Thanks in advance.

**Comment by bamless** [comment]
Hi, glad you find it interesting!
As for the questions:

For the first question: Yes -- The language is fully garbage collected, you don't have to worry about freeing allocations. J* implements a tracing garbage collector not too dissimilar to those of other dynamic languages (such as, for example, lua).

For the second:
The language supports multiple ways to register C functions for being callable from J* depending on whether you are embedding the language or using the CLI.

# Extending the language from the embedder side

## Using the API

The simplest approach would be binding functions directly using the API from the embedder program:
```c
#include <assert.h>
#include <errno.h>
#include <jstar/jstar.h>
#include <string.h>
#include <time.h>

static bool now(JStarVM* vm) {
    // Check that the first argument is a string and get it from the stack
    JSR_CHECK(String, 1, "format");
    const char* format = jsrGetString(vm, 1);

    // Get the current time
    time_t rawtime;
    time(&rawtime);

    struct tm* timeinfo = localtime(&rawtime);

    // Convert the time to a string
    char buffer[100];
    if(strftime(buffer, sizeof(buffer), format, timeinfo) == 0) {
        // In case of error raise an exception
        jsrRaise(vm, "Exception", strerror(errno));
        return false;
    }

    // Push the result on the stack and return it
    jsrPushString(vm, buffer);
    return true;
}

int main() {
    JStarConf conf = jsrGetConf();
    JStarVM* vm = jsrNewVM(&conf);
    jsrInitRuntime(vm);

    // Push a native directly using the API
    jsrPushNative(vm, JSR_MAIN_MODULE, "now", &now, 1);
    jsrSetGlobal(vm, JSR_MAIN_MODULE, "now");
    jsrPop(vm);

    // Call the function
    JStarResult res = jsrEvalString(vm, "<main>", "print(now('%Y-%m-%d %H:%M:%S'))");
    assert(res == JSR_SUCCESS);

    jsrFreeVM(vm);
}
```
## Loading shared objects (`so`s, `dll`s)

If you want more flexibility, you can instead use the module importing API to directly load shared objects (`.so`s, `.dll`s) and bind c functions to `native` declarations inside your scripts.  
Unfortunately, I have to yet get around in writing documentation on how to achieve this from the embedder side, but you can take a look at the `jstar` cli app, as it uses the API to load shared objects in the [import.c](https://github.com/bamless/jstar/blob/master/apps/jstar/import.c#L199) file.

# Extending the language when using the CLI (`jstar` binary)

As mentioned above, the J* CLI already supports extending modules with native functions coming from a shared object. A simple setup would look like:

natives.c
```c
#include <jstar/jstar.h>

static bool nativeFunc(JStarVM* vm) {
    printf("Look Ma! I'm a native function!\n");
    jsrPushNull(vm);
    return true;
}

static bool nativeMethod(JStarVM* vm) {
    printf("Look Ma! I'm a native method!\n");
    jsrPushNull(vm);
    return true;
}

static JStarNativeReg registry[] = {
    JSR_REGFUNC(nativeFunc, &nativeFunc)
    JSR_REGMETH(NativeClass, nativeMethod, &nativeMethod)
    JSR_REGEND
};

JSTAR_API JStarNativeReg *jsrOpenModule() {
    return registry;
}
```
natives.jsr
```
native nativeFunc()

class NativeClass
    native nativeMethod()
end
```

Compile the natives into a shared library:
```bash
gcc -Djstar_EXPORTS=1 -ljstar -fPIC -shared -o natives.so natives.c
```
Then put natives.so and natives.jsr files in the same path:

```
$ jstar
J* Version 2.0.0
GNU 14.1.1 on Linux
J*>> import natives
J*>> natives.nativeFunc()
Look Ma! I'm a native function!
J*>> natives.NativeClass().nativeMethod()
Look Ma! I'm a native method!
J*>> _
```

Basically, at import time, the CLI will look for a `so` or `dll` file with the same name of the imported module inside the same path where it has resolved the `jsr` file. If that shared object exposes a `jsrOpenModule` returining a `JStarNativeReg` , it will try to bind every `native` declaration in the `jsr` file to a native function in the registry.

> NOTE
>
> This resolution strategy is only the specific way the CLI app chooses to resolve native extension modules, it is not dicated by the language API. When a user embeds J* in his own program he can choose the resolution strategy for both import and natives. For example, it is not difficult to imagine a setup in which all natives are precompiled in a single giant `.so` file, and the embedder includes this registry in every import regardless of path.

If you want to see a more complex project meant to be used with the CLI native registration API, you can take a look at [event_horizon](https://github.com/bamless/event_horizon).

# Bonus: Rust bindings

I don't know if you would be interested in this, but lately I've been working on a library for embedding J* in rust. You can find it [here](https://github.com/bamless/jstar-rs). It is not yet complete, but I'm actively working on it to reach parity with the C API soon.

**Comment by bamless** [comment]
Sorry for the wall of text :sweat_smile:, let me know if anything is unclear

**Comment by kcvinker** [comment]
@bamless 
Thanks a lot for the detailed reply and code samples. My aim was to call windows api functions from `J*`.  Anyhow, directly using the API from the embedder program seems nice. I am using a language called `C3` instead of C.

**Comment by bamless** [comment]
Nice! I'm going to close this issue, in case you have any other questions or issues you can reopen it.
